
# Download and apply manifest
- name: Download ingress-nginx manifest to the cluster.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ nginx_controller_version }}/deploy/static/provider/cloud/deploy.yaml
    dest: ~/deployments/ingress-nginx-v{{ nginx_controller_version }}.yaml
    mode: '0664'
  when: kubernetes_role == 'master'


- name: Apply metrics-server manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: ~/deployments/ingress-nginx-v{{ nginx_controller_version }}.yaml
  when: kubernetes_role == 'master'


- name: Wait until it is ready to run the next command
  command: "kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s"
  when: kubernetes_role == 'master'