---
- hosts: k8s
  become: true
  roles:
    - role: rpi_settings
      tags: ['settings']
      vars:
        ufw_defaults:
          - { direction: "incoming", policy: "deny" }
          - { direction: "outgoing", policy: "deny" }
        ufw_rules:
          - { rule: "allow", port: "22", proto: "tcp" }
          - { rule: "allow", port: "22", proto: "udp" }
        fail2ban_ignored_ips:
          - 127.0.0.1
          - 192.168.1.61
          - 192.168.1.48
        fail2ban_bantime: 24h
        fail2ban_maxretry: 3
        fail2ban_findtime: 10m

    - role: docker
      tags: ['docker']
