---
- name: Check if node has already joined.
  stat:
    path: /root/.kube/config
  register: kubernetes_node_join_stat

- name: Join node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
  when: kubernetes_node_join_stat.stat.exists
