---
- name: Check if node has already joined.
  stat:
    path: ~/.kube/config
  register: kubernetes_node_join_stat

- name: Join node to Kubernetes master
  become: true
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  when: kubernetes_node_join_stat.stat.exists
