---

- name: update hostname {{ inventory_hostname }} (1/3)
  hostname: 
    name: "{{ inventory_hostname }}"
  register: hostname_change_1

- name: update hostname {{ inventory_hostname }} (2/3)
  copy: 
    content: "{{ inventory_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
  register: hostname_change_2

- name: update hostname {{ inventory_hostname }} (2/3)
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ inventory_hostname }}"
    backup: true
    state: present