---

- name: Create project directories
  ansible.builtin.file:
    path: "{{ item.key }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: docker
  with_dict: "{{ directories }}"

- name: Add the docker-compose manifest
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ directories['project_dir'] }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: docker
  notify: Restart docker-compose stack

- name: Start docker-compose stack
  community.docker.docker_compose:
    project_src: "{{ directories['project_dir'] }}"
    state: present
    stopped: no

- include_tasks: heimdall.yml

- name: Restart docker-compose stack
  community.docker.docker_compose:
    project_src: "{{ directories['project_dir'] }}"
    state: present
    restarted: yes