---
- hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml
        
  roles:
    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: karoui.docker
      tags: ['docker']

    - role: karoui.k8s-setup
      tags: ['kubernetes']
    
    - role: karoui.k8s-config
      tags: ['kubernetes']

    - role: karoui.k8s-deploy
      tags: ['kubernetes']