---
- hosts: k8s
  # become: yes

  vars_files:
    - vars/main.yml
        
  roles:
    - role: karoui.swap
      tags: ['swap']

    - role: karoui.docker
      tags: ['docker']

    - role: karoui.k8s-setup
      tags: ['k8s-setup']
    
    - role: karoui.k8s-kubectl
      tags: ['k8s-kubectl']

    - role: karoui.k8s-default-apps
      tags: ['k8s-apps']
      when: kubernetes_role == 'master'