# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
IMAGE_NAME = "ubuntu/xenial64"
BASE_IP="10.11.13"


boxes = [
  {:name => "master",   :ip => "#{BASE_IP}.11"},
  {:name => "worker-1", :ip => "#{BASE_IP}.12"},
  {:name => "worker-2", :ip => "#{BASE_IP}.13"}
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = IMAGE_NAME

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--groups", "/spark"]
  end

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
    end
  end

end