---
# This playbook assumes you already have the kubectl binary installed
# and available in the $PATH.
- name: Retrieve kubectl config file from the master server.
  fetch:
    src: "{{ kubectl_config_path }}"
    dest: "{{ kubectl_local_tmp_path }}"
    flat: yes
  when: kubernetes_role == 'master'