---
kubernetes_version: '1.21'
kubernetes_dashboard_version: '2.2.0'
kubernetes_calico_version: '3.18'
kubernetes_api_spec_version: 'kubeadm.k8s.io/v1beta2'

kubernetes_packages:
  - name: kubelet
    state: present
  - name: kubectl
    state: present
  - name: kubeadm
    state: present
  - name: kubernetes-cni
    state: present

kubernetes_role: master
kubernetes_cluster_name: "k8s-simple-cluster"
kubernetes_kubeadm_init_extra_opts: ""
kubernetes_skip_init: false

kubernetes_join_command_extra_opts: ""
kubernetes_allow_pods_on_master: true
kubernetes_enable_web_ui: true
kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/v{{ kubernetes_dashboard_version }}/aio/deploy/recommended.yaml

kubernetes_pod_network:
  cni: 'calico'
  cidr: '10.244.0.0/16'

kubernetes_kubeadm_kubelet_config_file_path: '/etc/kubernetes/kubeadm-kubelet-config.yaml'
kubernetes_config_kubelet_configuration:
  cgroupDriver: "cgroupfs"

kubernetes_config_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
    bindPort: 6443

kubernetes_config_cluster_configuration:
  clusterName: "{{ kubernetes_cluster_name }}"
  networking:
    podSubnet: "{{ kubernetes_pod_network.cidr }}"
  kubernetesVersion: "{{ kubernetes_version_kubeadm }}"

kubernetes_apiserver_advertise_address: ''
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
kubernetes_ignore_preflight_errors: 'all'

kubernetes_apt_release_channel: main
# Note that xenial repo is used for all Debian derivatives at this time.
kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_apt_release_channel }}"
kubernetes_apt_ignore_key_error: false
# Calico config files
kubernetes_calico_manifest_file: https://docs.projectcalico.org/v{{ kubernetes_calico_version }}/manifests/calico.yaml
