---
- name: Manage swap file entry in fstab.
  become: true
  mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "absent"

- name: Disable swap (if configured).
  become: true
  command: swapoff -a

- name: Ensure swap file doesn't exist (if configured).
  become: true
  file:
    path: "{{ swap_file_path }}"
    state: absent