---

- name: Install OpenVPN
  import_tasks: install.yml
  tags:
    - install

- name: setup openvpn server
  ansible.builtin.include_tasks:
    file: "setup-server.yml"

- name: start and enable openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: yes