---

- name: Add domains file
  template:
    src: "domains.sql.j2"
    dest: "{{ domains_sql_file }}"
    owner: "{{ pdns_user }}"
    group: "{{ pdns_group }}"
  register: domains_updated

- name: Update domains
  shell: "sqlite3 {{ item }} < {{ domains_sql_file }}"
  args:
    creates: "{{ item }}"
  with_items: "{{ pdns_backends.gsqlite3.database }}"
  when: domains_updated is defined
